### ISSUE TITLE
Get latest DolphinNext version using pre-built docker image

### ISSUE THREAD

**Issue by akshitvjain** [UMMS-Biocore/dolphinnext-docker#68]
The docker image for [dolphinnext-studio](https://hub.docker.com/r/ummsbiocore/dolphinnext-studio) provides DolphinNext version 1.2.29. Is there a way to get the latest version of DolphinNext (1.2.40) using the pre-built docker image.

**Comment by onuryukselen** [comment]
Hi, after entering docker container, and executing startup script, you can execute the following to update dolphinnext.
python /export/dolphinnext/scripts/updateDN.py

**Comment by akshitvjain** [comment]
Thank you that was helpful.
